### ISSUE TITLE
Dokumentace Invoice::date_paid

### ISSUE THREAD

**Issue by integer** [TwistoPayments/Twisto.php#2]
Na stránce https://www.twisto.cz/docs/v2/data/ nevidím popis atributu `Invoice::date_paid` ( https://github.com/TwistoPayments/Twisto.php/blob/master/src/Twisto/Invoice.php#L38 ). Najdeme zde datum zaplacení faktury zákazníkem Twistu a můžeme podle něj detekovat, zda se fakturu podaří stornovat?

**Comment by LukasHurych** [comment]
Ano, je to datum zaplacení faktury zákazníkem (popis atributu není v dokumentaci úmyslně, běžně by jej e-shop neměl potřebovat). Je pro tyto případy (resp. pro to zda se fakturu podaří označit jako vratku – return; storno je jiná situace, to jde pouze v případě, kdy faktura ještě nebyla aktivována).
